---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
  - repo: git@github.com:mschwager/jinjalint.git
    rev: master
    hooks:
      - id: jinjalint
